---
editor_options: 
  markdown: 
    wrap: 72
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 1
---

<hr>

# Join Our Sleep and Circadian Sciences Research!

<hr>

Are you passionate about sleep and circadian sciences? If you live in
Izmir, Turkey, and are curious about your light exposure and sleep
patterns, we invite you to volunteer in our research. Participate in our
questionnaires or field studies to contribute to groundbreaking
discoveries.

**Contact us today to explore these exciting opportunities!**

<hr>

<br><br><br>

<hr>

# Research areas

<hr>

-   **Better Light Exposure Metrics for All Species**

This project focuses on developing and standardizing light-exposure measurement methods tailored to different species. Our goal is to improve and regulate lighting conditions for pets, farm animals, and laboratory animals to support their health and well-being. We also aim to quantify and evaluate ecological light-pollution metrics to better understand environmental impacts, ultimately contributing to more effective conservation strategies.

-   **Measuring Light Exposure and Sensitivities in Everyday Life**

This project develops wearable melanopic lux monitors to capture personal light exposure in real-world environments. In parallel, we are creating mobile applications to collect data on sleep, behavior, mood, and cognition. This integrated approach enables us to examine how daily light exposure influences multiple aspects of life. We additionally investigate inter-individual differences in light sensitivity and work toward establishing more accurate ways to measure these sensitivities, their biological foundations, and their behavioral consequences.

-   **Acute Non-Visual Effects of Light**

This laboratory-based project investigates the immediate non-visual effects of precisely controlled light stimuli on cognition, mood, and neuroendocrine function. Our work combines eye-tracking, pupillometry, psychophysics, computerized cognitive tasks, and validated surveys to build a comprehensive picture of how light acutely influences the human brain and behavior.

-   **Optimizing Light Exposure in Educational Environments**

This project aims to enhance cognitive performance and promote healthier sleep patterns by optimizing lighting conditions in educational settings. By tailoring the timing, spectrum, and intensity of light, we seek to create learning environments that support both academic success and overall well-being.

-   **Cultural Adaptation in Sleep and Circadian Research**

This project focuses on translating, validating, and culturally adapting sleep and circadian assessment tools. By accounting for cultural differences in behavior, environment, and interpretation, we aim to strengthen meta-science practices and improve the reproducibility and global applicability of circadian and sleep research.

-   **Enhancing Health and Aging through Better Rhythm**

The project aims to investigate the associations between aging trajectories of sleep patterns, circadian rhythms, lighting and feeding behaviour, health, cognition, and mood. By understanding these relationships, the project seeks to develop targeted interventions that promote healthier aging.

<hr>

<br><br><br>

<hr>

# Collaborations

<hr>

-   MeLiDos - A prospective, multi-centric, cross-sectional cohort study
    to assess personal light exposure; funded by the European
    Partnership on Metrology, co-financed by the European Union’s
    Horizon. <https://www.melidos.eu/>

-   DLA - Toward a globally representative dataset of personal daylight exposure. <https://daylight.academy/projects/toward-a-globally-representative-dataset-of-personal-daylight-exposure-capacity-building-and-micro-grant-initiative/>

<hr>

<br><br><br>

<hr>

# Open positions

<hr>

Anyone interested in joining the group or collaborating is welcome to
contact us.

<hr>

<br><br><br>

<hr>

# Grants

<hr>

-   **Daylight Academy - A VELUX STIFTUNG initiative (2025-2027):** Toward a globally representative dataset of personal daylight exposure: capacity building and micro-grant initiative
    
-   **IZTECH-AUDP (2024-2026):** Development of a multi-spectrum display
    for home-based light testing and therapies

-   **TUBITAK-2209A (2024-2025):** Turkish translation of Light Exposure Behaviour Assesment (LEBA) and study of its validity and reliability
    
-   **TUBITAK-2209A (2024-2025):** Effect of Circadian Lighting Conditions on Photodormancy and Germination in Beans

-   **TUBITAK-1002 (2024-2025):** Measurement of Light Exposure in Daily
    Life Using Wearable Light Loggers

-   **The University of Manchester Research Collaboration Fund (2022-2023):** Measuring Effects of Light Exposure on Activity,
    Sleep and Human Performance

-   **UKRI BBSRC - ICURe Lean Launch Programme (2022):** Animal-centric
    approach to measuring light intensity

<hr>
