---
editor_options: 
  markdown: 
    wrap: 72
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
---

```{=html}
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
```

To view the full list of my citations and publications, please visit my
[Google
Scholar](https://scholar.google.com.tr/citations?user=q4pq0fIAAAAJ&hl=tr)
profile. <br>

<hr>

# 2025

<hr>

-   Dashti H.S., ..., **Didikoglu A.**. 2025. Meal timing trajectories in older adults and their associations with morbidity, genetic profiles, and mortality. *Communications Medicine* <https://doi.org/10.1038/s43856-025-01035-x>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1038/s43856-025-01035-x"}
:::

<hr>

-   Woelders T., **Didikoglu A.**, et al. 2025. Pupillometric and perceptual approaches provide independent estimates of melanopsin activity in humans. *Sleep* <https://doi.org/10.1093/sleep/zsae289>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1093/sleep/zsae289"}
:::

<hr>

-   Duijnhoven J.V., ..., **Didikoglu A.**, et al. 2025. Measuring light exposure in daily life: A review of wearable light loggers. *Building and Environment* <https://doi.org/10.1016/j.buildenv.2025.112771>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.buildenv.2025.112771"}
:::

<hr>

-   Jervis S., ..., **Didikoglu A.**, et al. 2025. Narcolepsy genetic variants associated with sleep efficiency in a community dwelling older cohort. *Sleep Science and Practice* <https://doi.org/10.1186/s41606-025-00135-w>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1186/s41606-025-00135-w"}
:::

<hr>

# 2024

<hr>

-   McDowell R.J., **Didikoglu A.**, et al. 2024. Beyond Lux: methods for species and photoreceptor-specific quantification of ambient light for mammals. *BMC Biology* <https://doi.org/10.1186/s12915-024-02038-1>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1186/s12915-024-02038-1"}
:::

<hr>

-   Guidolin C., ..., **Didikoglu A.**, et al. 2024. Protocol for a prospective, multicentre, cross-sectional cohort study to assess personal light exposure. *BMC Public Health* <https://doi.org/10.1186/s12889-024-20206-4>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1186/s12889-024-20206-4"}
:::

<hr>

-   Alkan C., **Didikoglu A.**, et al. 2024. Assessment of the validity and reliability of edinburgh postpartum depression scale in Turkish men. *Journal of Perinatal Medicine* <https://doi.org/10.1515/jpm-2024-0026>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1515/jpm-2024-0026"}
:::

<hr>

-   Celik M., **Didikoglu A.**, et al. 2024. Optimizing lighting design in educational settings for enhanced cognitive performance: A literature review. *Energy and Buildings* <https://doi.org/10.1016/j.enbuild.2024.115180>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.enbuild.2024.115180"}
:::

<hr>

-   **Didikoglu A.**, et al. 2024. Depression in older adults and its
    associations with sleep and synaptic density. *Journal of Affective Disorders* <https://doi.org/10.1016/j.jad.2024.08.186>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.jad.2024.08.186"}
:::

<hr>

-   Lucas R.J., ..., **Didikoglu A.**, et al. 2024. Recommendations for measuring and
    standardizing light for laboratory mammals to improve welfare and
    reproducibility in animal research. *PLOS Biology* <https://doi.org/10.1371/journal.pbio.3002535>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1371/journal.pbio.3002535"}
:::

<hr>

-   Mohammmadian N., **Didikoglu A.**, et al. 2024. A wrist worn
    Internet-of-Things sensor node for wearable equivalent daylight
    illuminance monitoring. *IEEE Internet of Things Journal*
    <https://doi.org/10.1109/JIOT.2024.3355330>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1109/JIOT.2024.3355330"}
:::

<hr>

# 2023

<hr>

-   Faulkner S., **Didikoglu A.**, et al. 2023. Light-Dark and Activity
    Rhythm Therapy (L-DART) to improve sleep in people with
    schizophrenia spectrum disorders: a single group mixed methods study
    of feasibility, acceptability and adherence. *Clocks & Sleep*
    <https://doi.org/10.3390/clockssleep5040048>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.3390/clockssleep5040048"}
:::

<hr>

-   **Didikoglu A.**, et al. 2023. Associations between light exposure
    and sleep timing and sleepiness while awake in a sample of UK adults
    in everyday life. *PNAS* <https://doi.org/10.1073/pnas.2301608120>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1073/pnas.2301608120"}
:::

<hr>

-   Maharani A., **Didikoglu A.**, et al. 2023. Education mediating the
    associations between early life factors and frailty: a
    cross-sectional study of the UK Biobank. *BMJ Open*
    <http://doi.org/10.1136/bmjopen-2021-057511>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1136/bmjopen-2021-057511"}
:::

<hr>

-   Jervis S., et al. 2023. Narcolepsy Associated Genetic Variants
    Associated with Impaired Cognition in A Community Dwelling Older
    Cohort. *Journal of Sleep Disorders & Therapy*
    <https://www.longdom.org/open-access/narcolepsy-associated-genetic-variants-associated-with-impaired-cognition-in-a-community-dwelling-older-cohort-102647.html>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-handle="Narcolepsy Associated Genetic Variants Associated with Impaired Cognition in A Community Dwelling Older Cohort"}
:::

<hr>

# 2022

<hr>

-   Gardesevic M., **Didikoglu A.**, et al. 2022. Brighter Time: A
    Smartphone App Recording Cognitive Task Performance and Illuminance
    in Everyday Life. *Clocks & Sleep*
    <https://doi.org/10.3390/clockssleep4040045>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.3390/clockssleep4040045"}
:::

<hr>

-   **Didikoglu A.**, et al. 2022. Associations between chronotype and
    employment status in a longitudinal study of an elderly population.
   *Chronobiology International*
    <https://doi.org/10.1080/07420528.2022.2071158>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1080/07420528.2022.2071158"}
:::

<hr>

# 2021

<hr>

-   **Didikoglu A.**, et al. 2021. The effect of season of birth on
    brain epigenome-wide DNA methylation of older adults. *Journal of Developmental Origins of Health and Disease*
    <https://doi.org/10.1017/S2040174421000453>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1017/S2040174421000453"}
:::

<hr>

-   **Didikoglu A.**, et al. 2021. Early life factors and COVID-19
    infection in England: A prospective analysis of UK Biobank
    participants. *Early Human Development*
    <https://doi.org/10.1016/j.earlhumdev.2021.105326>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.earlhumdev.2021.105326"}
:::

<hr>

# 2020

<hr>

-   Bethany H., **Didikoglu A.**, et al. 2020. Epigenetic regulation of
    BMAL1 with sleep disturbances and Alzheimer’s Disease. *Journal of Alzheimer's Disease* <https://doi.org/10.3233/JAD-200634>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.3233/JAD-200634"}
:::

<hr>

-   **Didikoglu A.**, et al. 2020. Interactions between season of birth,
    chronological age and genetic polymorphisms in determining
    later-life chronotype. *Mechanisms of Ageing and Development*
    <https://doi.org/10.1016/j.mad.2020.111253>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.mad.2020.111253"}
:::

<hr>

-   **Didikoglu A.**, et al. 2020. Seasonality and season of birth
    effect in the UK Biobank cohort. *American Journal of Human Biology*
    <https://doi.org/10.1002/ajhb.23417>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1002/ajhb.23417"}
:::

<hr>

# 2019

<hr>

-   **Didikoglu A.**, et al. 2019. Longitudinal change of sleep timing:
    association between chronotype and longevity in older adults.
    *Chronobiology International*
    <https://doi.org/10.1080/07420528.2019.1641111>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1080/07420528.2019.1641111"}
:::

<hr>

-   **Didikoglu A.**, et al. 2019. Longitudinal sleep efficiency in the
    elderly and its association with health. *Journal of Sleep Research*
    <https://doi.org/10.1111/jsr.12898>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1111/jsr.12898"}
:::

<hr>

<br><br><br>

<hr>

# Conference Proceedings

<hr>

-   Lui C., **Didikoglu A.**, et al. 2024. Meal Timing Trajectories and
    All-Cause Mortality in Older Adults. American Society of Nutrition,
    NUTRITION 2024 (June 2024, Chicago, USA). *Current Developments in Nutrition* <https://doi.org/10.1016/j.cdnut.2024.102783>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1016/j.cdnut.2024.102783"}
:::

<hr>

-   Lucas R.J., **Didikoglu A.**, et al. 2023. Spectrawear, an
    Open-Source, Reasonably Priced, Wearable Dosimeter Suitable for
    Longitudinal Monitoring of Light Exposure in Alpha-Opic Units in
    Everyday Life. Society for Light Treatment and Biological Rhythms,
    34th Annual Meeting (May 2023, SWITZERLAND). *Clocks & Sleep*
    <https://doi.org/10.3390/clockssleep5030031>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.3390/clockssleep5030031"}
:::

<hr>

-   **Didikoglu A.**, et al. 2021. Longitudinal Change of Sleep in the
    Elderly and Its Associations with Health. British Geriatrics
    Society, Autumn Meeting (November 2020, Manchester, UK). *Age and Ageing* <https://doi.org/10.1093/ageing/afab030.10>

::: {.altmetric-embed data-badge-type="medium-donut" data-badge-details="right" data-doi="10.1093/ageing/afab030.10"}
:::

<hr>
